# Generated by Django 2.2 on 2019-05-20 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('nationality', models.CharField(choices=[('KR', '한국'), ('JP', '일본'), ('TW', '대만')], max_length=20)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
